CREATE PROCEDURE SSHARM17."AddObsSpecAndMetricName" (
 obsspecname IN OBSERVATIONSPEC.OBSERVATIONSPECNAME%TYPE,
 obsdesc IN OBSERVATIONSPEC.DESCRIPTION%TYPE)
AS
BEGIN
	INSERT INTO OBSERVATIONSPEC ( OBSERVATIONSPECNAME, DESCRIPTION )
	   VALUES (obsspecname,obsdesc);
	
	
	
END;