CREATE PROCEDURE SSHARM17."AddObservationProc" (
 obsid IN OBSERVATION.OBSERVATIONID%TYPE,
 obstime IN OBSERVATION.OBSERVATIONTIME%TYPE,
 obsrectime IN OBSERVATION.RECORDEDTIME%TYPE,
 ssn IN OBSERVATION.PATIENTSSN%TYPE)
AS
BEGIN
   INSERT INTO OBSERVATION (OBSERVATIONID, OBSERVATIONTIME, RECORDEDTIME, PATIENTSSN) VALUES(obsid, obstime, rectime, ssn);

END;