CREATE PROCEDURE SSHARM17."clearLimitAlerts"
AS
BEGIN
   	UPDATE ALERT SET ALERTACTION='Clear', ALERTCLEARDATE=SYSDATE
	WHERE ALERTID IN
	(
		SELECT A.ALERTID FROM PATIENT P, LIMITS L, OBSERVATION O, OBSERVATIONDETAILS OD, ALERT A, ALERTFORLIMIT AL
		WHERE O.OBSERVATIONID = OD.OBSERVATIONID 
		AND A.PATIENTSSN = P.PATIENTSSN
		AND AL.LIMITID = L.LIMITID
		AND AL.ALERTID = A.ALERTID
		AND AL.OBSERVATIONID = O.OBSERVATIONID
		AND L.OBSERVATIONSPECNAME = OD.OBSERVATIONSPECNAME
		AND L.METRICNAME = OD.METRICNAME
		AND OD.OBSERVATIONVALUE <= L.UPPERLIMIT 
		AND OD.OBSERVATIONVALUE >= L.LOWERLIMIT
		AND A.ALERTACTION <> 'Clear'
	);
END;