CREATE OR REPLACE PROCEDURE SSHARM17."deleteSecondarySupporter" (
   "patientSSN"          IN VARCHAR2,
   "hsSSN"               IN VARCHAR2)
AS
BEGIN

	DELETE FROM PATIENTTOHEALTHSUPPORTER WHERE PATIENTSSN="patientSSN" and PRIMARYSECONDARY="Secondary";

END;