CREATE OR REPLACE PROCEDURE SSHARM17."generateRecommendationAlerts"
AS
	CURSOR patientRecommendation 
		IS 
			SELECT DISTINCT P.PatientSSN as patientSSN, RC.recommendationID as recommendationId  FROM 
			PATIENT P, RECOMMENDATION RC, FREQUENCY F
			WHERE 
			RC.FREQUENCYNAME = F.FREQUENCYNAME AND
			RC.RECOMMENDATIONID IN (
			  SELECT r.RECOMMENDATIONID FROM RECOMMENDATION r
				WHERE r.RECOMMENDATIONID NOT IN (SELECT r.RECOMMENDATIONID FROM RECOMMENDATIONFORDISEASE r UNION SELECT r.RECOMMENDATIONID FROM RECOMMENDATIONFORPATIENT r)
				UNION
				SELECT r.RECOMMENDATIONID FROM RECOMMENDATIONFORDISEASE r, SICKHASMAJORDISEASE s 
				WHERE s.PATIENTSSN = P.PATIENTSSN
				AND s.DISEASENAME = r.DISEASENAME
				UNION
				SELECT r.RECOMMENDATIONID FROM RECOMMENDATIONFORPATIENT r
				WHERE r.PATIENTSSN = P.PATIENTSSN
			) AND
			NOT EXISTS(
			  SELECT * FROM OBSERVATION O, OBSERVATIONDETAILS OD
			  WHERE O.OBSERVATIONID = OD.OBSERVATIONID AND
			  OD.OBSERVATIONSPECNAME = RC.OBSERVATIONSPECNAME AND
			  O.OBSERVATIONTIME > (SYSDATE-F.DURATION)
			  )
			ORDER BY RC.RECOMMENDATIONID;
			
	observationCount INTEGER;
	entriesFound INTEGER;
	existingAlertClear INTEGER;
	alertId INTEGER;
	recommendationIds "RecommendationIds";
BEGIN
	FOR recommendationRow IN patientRecommendation LOOP
		SELECT count(*) INTO observationCount FROM OBSERVATION O, OBSERVATIONDETAILS OD, RECOMMENDATION r, FREQUENCY f
  		WHERE O.OBSERVATIONID = OD.OBSERVATIONID AND
		r.RECOMMENDATIONID = recommendationRow.recommendationID AND
  		OD.OBSERVATIONSPECNAME = r.OBSERVATIONSPECNAME AND
		O.PATIENTSSN = recommendationRow.PATIENTSSN AND
		r.FREQUENCYNAME = f.FREQUENCYNAME AND
  		O.OBSERVATIONTIME > (SYSDATE-f.DURATION);
		
		IF observationCount = 0 THEN
			SELECT count(*) INTO entriesFound FROM ALERT a, ALERTFORRECOMMENDATION a1, RECOMMENDATION r, FREQUENCY f
			WHERE a.ALERTID = a1.ALERTID
			AND a.PATIENTSSN = recommendationRow.PATIENTSSN
			AND r.RECOMMENDATIONID = recommendationRow.recommendationID
			AND a1.RECOMMENDATIONID = r.RECOMMENDATIONID
			AND r.FREQUENCYNAME = f.FREQUENCYNAME
			AND a.ALERTDATE > (SYSDATE-f.DURATION);
			
			alertId := ALERTS_SEQ.NEXTVAL;
			
			IF entriesFound = 0 THEN
				INSERT INTO ALERT (ALERTID,ALERTTYPE,PATIENTSSN,ALERTACTION,ALERTDATE)
				VALUES (alertId, 'LOW_ACTIVITY', recommendationRow.patientSSN,'New',SYSDATE);
				INSERT INTO ALERTFORRECOMMENDATION (ALERTID, RECOMMENDATIONID) VALUES(alertId, recommendationRow.recommendationID);	
			END IF;
			
		ELSE
			
			UPDATE ALERT SET ALERTACTION='Clear', ALERTCLEARDATE=SYSDATE
			WHERE ALERTID IN (
							SELECT a.ALERTID 
							FROM ALERT a, ALERTFORRECOMMENDATION a1, RECOMMENDATION r, FREQUENCY f
							WHERE a.ALERTID = a1.ALERTID
							AND a.PATIENTSSN = recommendationRow.PATIENTSSN
							AND r.RECOMMENDATIONID = recommendationRow.recommendationID
							AND a1.RECOMMENDATIONID = r.RECOMMENDATIONID
							AND r.FREQUENCYNAME = f.FREQUENCYNAME
							AND a.ALERTDATE > (SYSDATE-f.DURATION)
							AND a.ALERTACTION <> 'Clear'
							);
		
		END IF;
		
		
	END LOOP;
   
END;